---
title: "Semen microbiome - Clinical Covariate Plots"
output: html_notebook
---

```{r "setup", include=FALSE}
require("knitr")
opts_knit$set(root.dir='./')
```

Import the required packages
```{r, include=FALSE}
library(readr)
library(readxl)
library(ggplot2)
library(dplyr)
library(ggstatsplot)
library(ggpubr)

dir.create('./Analysis Figures/ClinicalCovariates_Figures/', recursive = T)
```

```{r}
studyMetadata <- read_csv("../Data/ClinicalData.csv")

colnames(studyMetadata)[colnames(studyMetadata) == 'ROS...10'] <- 'ROS'
colnames(studyMetadata)[colnames(studyMetadata) == 'ROS...24'] <- 'ROSContinuous'

diversityMeasures <- read_csv('../Data/Alpha_Diversity_Measures_ASVs.csv')

studyMetadata <- merge(diversityMeasures, studyMetadata, on='Sample Name')

cstAssignments <- read_csv('./Results/CST_Analysis/Semen_CST_GeneraAssignments.csv')

studyMetadata <- merge(cstAssignments, studyMetadata, by.x='SampleID', by.y='Sample Name')
```
```{r}
# Color palette from matplotlib/seaborn for reference
# mpl_color_palette <- c("#4C72B0", "#DD8452", "#55A868", "#C44E52", "#8172B3")


ROS_Boxplot <- ggplot(subset(studyMetadata, Classification != 'Female factor'), aes(x=Classification, y=as.numeric(`ROSContinuous`), col=Classification)) + geom_boxplot(alpha=0.6, outlier.shape=NA) + scale_y_continuous(trans=scales::pseudo_log_trans(base = 10)) + geom_jitter() + theme_classic() + ylab('Reactive Oxygen Species (ROS)')

ggsave('./Analysis Figures/ClinicalCovariates_Figures/ROS_Boxplot_StudyGroups.svg', ROS_Boxplot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/ROS_Boxplot_StudyGroups.png', ROS_Boxplot, dpi=300)


SpermConcentration_Boxplot <- ggplot(subset(studyMetadata, Classification != 'Female factor'), aes(x=Classification, y=`Concentration (million/ml)`, col=Classification)) + geom_boxplot(alpha=0.6, outlier.shape=NA) + geom_jitter() + theme_classic() + ylab('Concentration (million/ml)')  + scale_y_continuous(trans=scales::pseudo_log_trans(base = 10)) #  + geom_hline(aes(yintercept=15))

ggsave('./Analysis Figures/ClinicalCovariates_Figures/Concentration_Boxplot_StudyGroups.svg', SpermConcentration_Boxplot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Concentration_Boxplot_StudyGroups.png', SpermConcentration_Boxplot, dpi=300)

BactLoad_Boxplot <- ggplot(subset(studyMetadata, Classification != 'Female factor'), aes(x=Classification, y=`Total 16s rRNA copy per mL`, col=Classification)) + geom_boxplot(alpha=0.6, outlier.shape=NA) + geom_jitter() + theme_classic() + ylab('Bacterial Concentration')  + scale_y_continuous(trans=scales::pseudo_log_trans(base = 10)) #  + geom_hline(aes(yintercept=15))

ggsave('./Analysis Figures/ClinicalCovariates_Figures/BactLoad_Boxplot_StudyGroups.svg', BactLoad_Boxplot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/BactLoad_Boxplot_StudyGroups.png', BactLoad_Boxplot, dpi=300)


ROS_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, (Classification != 'Female factor') & (`ROS` != 'no data')),
  x                = `ROS`,
  y                = Classification, 
  xlab             = "ROS",
  legend.title     = "ROS",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. <3.77 RLU/s`="#00BFC4", `2. >3.77 RLU/s`="#F8766D"))
 
ggsave('./Analysis Figures/ClinicalCovariates_Figures/ROS_StudyGroups_NoNA.svg', ROS_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/ROS_StudyGroups_NoNA.png', ROS_chiSqPlot, dpi=300)

ROS_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, (Classification != 'Female factor')),
  x                = `ROS`,
  y                = Classification, 
  xlab             = "ROS",
  legend.title     = "ROS",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. <3.77 RLU/s`="#00BFC4", `2. >3.77 RLU/s`="#F8766D", `no data`="#619CFF"))
 
ggsave('./Analysis Figures/ClinicalCovariates_Figures/ROS_StudyGroups.svg', ROS_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/ROS_StudyGroups.png', ROS_chiSqPlot, dpi=300)


SemenQuality_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = "Semen quality",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Semen quality",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. Normal`="#00BFC4", `2. Abnormal`="#F8766D"))

ggsave('./Analysis Figures/ClinicalCovariates_Figures/SemenQuality_StudyGroups.svg', SemenQuality_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/SemenQuality_StudyGroups.png', SemenQuality_chiSqPlot, dpi=300)

DNAFrag_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = `DNA Fragmentation`,
  y                = Classification, 
  xlab             = "DNA Fragmentation",
  legend.title     = "DNA Fragmentation",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. Low`="#00BFC4", `2. High`="#F8766D"))
 
ggsave('./Analysis Figures/ClinicalCovariates_Figures/DNAFrag_StudyGroups.svg', DNAFrag_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/DNAFrag_StudyGroups.png', DNAFrag_chiSqPlot, dpi=300)

DNAFrag_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, (Classification != 'Female factor') & (`DNA Fragmentation` != 'No data')),
  x                = `DNA Fragmentation`,
  y                = Classification, 
  xlab             = "DNA Fragmentation",
  legend.title     = "DNA Fragmentation",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. Low`="#00BFC4", `2. High`="#F8766D"))
 
ggsave('./Analysis Figures/ClinicalCovariates_Figures/DNAFrag_StudyGroups_NoNA.svg', DNAFrag_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/DNAFrag_StudyGroups_NoNA.png', DNAFrag_chiSqPlot, dpi=300)


SpermCountTotal_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = "Total sperm count",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Total sperm count",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. >39 M`="#00BFC4", `2. <39 M`="#F8766D"))
ggsave('./Analysis Figures/ClinicalCovariates_Figures/SemenQuality_StudyGroups.svg', SpermCountTotal_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/SemenQuality_StudyGroups.png', SpermCountTotal_chiSqPlot, dpi=300)


viscosity_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = "Viscosity",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Viscosity",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. Optimal`="#00BFC4", `2. Viscous`="#F8766D", `no data`="#619CFF"))

ggsave('./Analysis Figures/ClinicalCovariates_Figures/Viscosity_StudyGroups.svg', viscosity_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Viscosity_StudyGroups.png', viscosity_chiSqPlot, dpi=300)


TotalMotility_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = "Total motility",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Total motility",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. >40%`="#00BFC4", `2. <40%`="#F8766D",  `no data`="#619CFF"))
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Total motility_StudyGroups.svg', TotalMotility_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Total motility_StudyGroups.png', TotalMotility_chiSqPlot, dpi=300)


studyMetadata$`Prog motility` <- factor(studyMetadata$`Prog motility`, levels=c('1. >32%', '2. <32%'))
ProgMotility_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = "Prog motility",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Prog motility",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. >32%`="#00BFC4", `2. <32%`="#F8766D"))
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Prog Motility_StudyGroups.svg', ProgMotility_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Prog Motility_StudyGroups.png', ProgMotility_chiSqPlot, dpi=300)


Morphology_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, Classification != 'Female factor'),
  x                = "Morphology",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Morphology",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`no data`="#619CFF", `1. >4%`="#00BFC4", `2. <4%`="#F8766D"))
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Morphology_StudyGroups.svg', Morphology_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Morphology_StudyGroups.png', Morphology_chiSqPlot, dpi=300)


Morphology_chiSqPlot <-  
  ggbarstats(
  data             = subset(studyMetadata, (Classification != 'Female factor') & (Morphology != 'no data')),
  x                = "Morphology",
  y                = Classification, 
  xlab             = "Classification",
  legend.title     = "Morphology",
  ggplot.component = list(ggplot2::scale_x_discrete(guide = ggplot2::guide_axis(n.dodge = 2))),
  palette = 'Set2'
) +   scale_fill_manual(values = c(`1. >4%`="#00BFC4", `2. <4%`="#F8766D"))
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Morphology_StudyGroups_NoNA.svg', Morphology_chiSqPlot, dpi=300)
ggsave('./Analysis Figures/ClinicalCovariates_Figures/Morphology_StudyGroups_NoNA.png', Morphology_chiSqPlot, dpi=300)
```